# Generated by Django 5.2 on 2025-04-23 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_certificate_created_at_alter_certificate_image_and_more'),
        ('specialists', '0003_alter_subscriptionplan_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard')], default='visa', max_length=20)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Paid', max_length=10)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.person')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.specialist')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.subscriptionplan')),
            ],
        ),
    ]
