# Generated by Django 5.2 on 2025-04-23 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('specialists', '0003_alter_subscriptionplan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='general_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='specialists.generalplan'),
            preserve_default=False,
        ),
    ]
