# Generated by Django 5.2 on 2025-04-23 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_general_plan'),
        ('specialists', '0003_alter_subscriptionplan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='general_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialists.generalplan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialists.subscriptionplan'),
        ),
    ]
