# Generated by Django 5.2 on 2025-04-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
