# Generated by Django 5.2 on 2025-04-22 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Femele', 'Femele')], max_length=8)),
                ('birth_date', models.DateField()),
                ('specialization_certificate', models.FileField(upload_to='certificates/')),
                ('specialty', models.CharField(choices=[('clinical', 'Clinical Nutrition'), ('weight', 'Weight Management'), ('children', 'Pediatric Nutrition'), ('women', 'Womens Nutrition'), ('chronic', 'Chronic Conditions'), ('vegan', 'Vegan/Vegetarian Nutrition'), ('seniors', 'Geriatric Nutrition'), ('disorders', 'Eating Disorders'), ('preventive', 'Preventive Nutrition')], max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Certificates', to='accounts.specialist')),
            ],
        ),
    ]
