# Generated by Django 5.2 on 2025-04-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='image',
            field=models.ImageField(default='images/default_profile.jpg', upload_to='images/'),
        ),
    ]
