# Generated by Django 5.2 on 2025-04-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_specialist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.FileField(null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='chronic_diseases',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
