# Generated by Django 5.2 on 2025-05-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_person_gender_alter_specialist_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True),
        ),
    ]
