# Generated by Django 5.2 on 2025-05-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_director_birth_date_director_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='specialty',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('diabetes', 'Diabetes Nutrition'), ('hypertension', 'Hypertension Nutrition'), ('cholesterol', 'Cholesterol Management Nutrition'), ('women_health', 'Women Health'), ('children', 'Children Nutrition'), ('seniors', 'Senior Nutrition'), ('vegan', 'Vegan / Vegetarian'), ('digestive', 'Digestive Health Nutrition'), ('immune', 'Immune Support Nutrition'), ('eating_disorders', 'Eating Disorders Nutrition'), ('general_health', 'General Health')], max_length=30),
        ),
    ]
