# Generated by Django 5.2 on 2025-04-22 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generalplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('plan_file', models.FileField(upload_to='general_plans/')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_plans', to='accounts.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('plan_type', models.CharField(choices=[('clinical', 'Clinical Nutrition'), ('weight', 'Weight Management'), ('children', 'Pediatric Nutrition'), ('women', 'Womens Nutrition'), ('chronic', 'Chronic Conditions'), ('vegan', 'Vegan/Vegetarian Nutrition'), ('seniors', 'Geriatric Nutrition'), ('disorders', 'Eating Disorders'), ('preventive', 'Preventive Nutrition')], max_length=30)),
                ('duration', models.CharField(choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('12_months', '12 Months')], max_length=20)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='images/plans/')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='accounts.specialist')),
            ],
        ),
    ]
