# Generated by Django 5.2 on 2025-04-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0002_alter_subscriptionplan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.CharField(blank=True, choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('12_months', '12 Months')], max_length=20, null=True),
        ),
    ]
