# Generated by Django 5.2 on 2025-04-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_certificate_created_at_alter_certificate_image_and_more'),
        ('specialists', '0004_mealcheck_subscribermeal_subscriberplan'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcheck',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subscription'),
        ),
        migrations.AddField(
            model_name='mealcheck',
            name='subscriber_meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.subscribermeal'),
        ),
        migrations.AddField(
            model_name='subscriberplan',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.specialist'),
        ),
        migrations.AddField(
            model_name='subscribermeal',
            name='subscriber_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.subscriberplan'),
        ),
    ]
