# Generated by Django 5.2 on 2025-05-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0005_mealcheck_subscription_mealcheck_subscriber_meal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalplan',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalplan',
            name='plan_type',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('diabetes', 'Diabetes Nutrition'), ('hypertension', 'Hypertension Nutrition'), ('cholesterol', 'Cholesterol Management Nutrition'), ('women_health', 'Women Health'), ('children', 'Children Nutrition'), ('seniors', 'Senior Nutrition'), ('vegan', 'Vegan / Vegetarian'), ('digestive', 'Digestive Health Nutrition'), ('immune', 'Immune Support Nutrition'), ('eating_disorders', 'Eating Disorders Nutrition'), ('general_health', 'General Health')], default='general_health', max_length=30),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('diabetes', 'Diabetes Nutrition'), ('hypertension', 'Hypertension Nutrition'), ('cholesterol', 'Cholesterol Management Nutrition'), ('women_health', 'Women Health'), ('children', 'Children Nutrition'), ('seniors', 'Senior Nutrition'), ('vegan', 'Vegan / Vegetarian'), ('digestive', 'Digestive Health Nutrition'), ('immune', 'Immune Support Nutrition'), ('eating_disorders', 'Eating Disorders Nutrition'), ('general_health', 'General Health')], max_length=30),
        ),
    ]
