# Generated by Django 5.2 on 2025-05-04 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0006_generalplan_detail_generalplan_plan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
