# Generated by Django 5.2 on 2025-04-29 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0005_mealcheck_subscription_mealcheck_subscriber_meal_and_more'),
        ('users', '0002_subscription_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscriber_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specialists.subscriberplan'),
        ),
    ]
