# Generated by Django 5.2 on 2025-04-29 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscription_subscriber_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subscription'),
        ),
    ]
