# Generated by Django 5.2 on 2025-05-03 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_director_birth_date_director_gender'),
        ('specialists', '0005_mealcheck_subscription_mealcheck_subscriber_meal_and_more'),
        ('users', '0004_alter_progressreport_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPlanPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.person')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.generalplan')),
            ],
        ),
    ]
