# Generated by Django 5.2 on 2025-05-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_generalplanpurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalplanpurchase',
            old_name='plan',
            new_name='general_plan',
        ),
    ]
